version: '2'
services:
    attendance-app:
        image: attendance
        external_links:
            - attendance-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/attendance?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    attendance-mysql:
        extends:
            file: mysql.yml
            service: attendance-mysql
